version: "3.7"
services:
  db:
    command: server /data
    container_name: db
    environment:
      - DB_LEGA_IN_PASSWORD=lega_in
      - DB_LEGA_OUT_PASSWORD=lega_out
      - NOTLS=true
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "lega_out"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: neicnordic/sda-db:v1.4.0
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/data